### ISSUE TITLE
Is the 'sha256' missing in ascmhl

### ISSUE THREAD

**Issue by SiDu1860** [ascmitc/mhl#142]
Hi @ptrpfn ,

did some tests with the latest version of ascmhl cmd -version 0.9.3.
In the github documentation there are named all supported checksum types:

<img width="558" alt="Bildschirmfoto 2024-02-21 um 10 14 47" src="https://github.com/ascmitc/mhl/assets/36437904/ea42be71-ec25-48f2-8c85-4dee1215335a">

but it looks like the sha256 cannot be written and verified. If I for example generate an sh256 MHL checksum with our ARRI HDE Transcoder, then this will result in:

<img width="838" alt="Bildschirmfoto 2024-02-21 um 10 30 35" src="https://github.com/ascmitc/mhl/assets/36437904/59215707-4c65-4651-92e9-fb290cad0521">

Question: Will 'sha256' be supported in the future or should it be striken out of the github site and also in post-prod. tools for the verification?

**Comment by ptrpfn** [comment]
Hello Simon,

The hash format sha256 is not included in the specification and not implemented in the reference implementation. 

ASC MHL manifest XML files with a `<sha256>` hash format tag will not validate against the published `ASCMHL.xsd` and must be considered invalid ASC MHL files.

It seems as if the mention of "SHA256" in the README was a mistake or leftover from a time when the list of hash formats was still in discussion. We removed the mention of the SHA256 hash format from the README.

Sorry for any trouble caused by this mistake and thank you bringing that up.

Best,
Patrick
