### ISSUE TITLE
Add xxh128/xxh3 as hashing algorithm

### ISSUE THREAD

**Issue by ptrpfn** [ascmitc/mhl#27]
Currently `_xxhash.py` of the [ifduyue/python-xxhash](https://github.com/ifduyue/python-xxhash) packge doesn't expose an interface for xxh3/xxh128. Possible action would be opening an issue there for adding xxh128.

**Comment by ptrpfn** [comment]
Todo: check if it has been exposed in  the Python wrapper of the xxhash library in the meantime

**Comment by jwaggs** [comment]
These algorithms were added in version 2.0 of the python xxhash library we use.

**Comment by jwaggs** [comment]
Implemented in PR #57 - question now is should we change the default algorithm to the new xxhash since it is faster? We could even bump to the new xxhash 128 bit algorithm and get a larger collision space while still gaining faster performance.

See the relevant [Collision Comparisons](https://github.com/Cyan4973/xxHash/wiki/Collision-ratio-comparison) and [Performance Comparisons](https://github.com/Cyan4973/xxHash/wiki/Performance-comparison) for the different xxhash variants.

**Comment by jwaggs** [comment]
Per our meeting today - we have decided to change the default algorithm to be xxh3_128. 

This should be added to PR #57 prior to merge

**Comment by ptrpfn** [comment]
Merged PR #57
