### ISSUE TITLE
Split directory hashes into content and file system structure hashes

### ISSUE THREAD

**Issue by ptrpfn** [ascmitc/mhl#44]

**Comment by jwaggs** [comment]
PR #51 has a draft to solve the splitting of directory hashes into a "content" hash and a "structure" hash.

@ptrpfn modeled that algorithm off of the C4ID specification for "Calculating a C4 ID for Non-contiguous Blocks of Data". Below is the referenced c4 spec. Section 5.4.

[30MR-WD-ST-2114-C4ID-2017-01-17 V0 (1).pdf](https://github.com/ascmitc/mhl/files/5877386/30MR-WD-ST-2114-C4ID-2017-01-17.V0.1.pdf)

This is a good reference implementation, however it differs from our prior algorithm for generating directory level checksums. We should discuss the motivation behind a few of the decisions in the c4 spec and determine what algorithm choices best suit our use cases.

Algorithm differences to discuss:

1. Sort Order. 
   - Sort by checksum vs sort by path. In both cases, ascending lexicographic.
2. Content Deduplication. 
   - C4 removes duplicates. Prior algorithm does not.
3. Multiple passes over content.
   - The c4 algorithm halves the digest list over multiple passes by pairing and rehashing prior digests. What is the motivation for this "halving" process in the c4 specification?

**Comment by ptrpfn** [comment]
I would propose to split up the discussion into two topics:
* the algorithm for the content hash and 
* the algorithm for the structure hash.
 
Both algorithms differ in some details (due to the different things they need to hash). For example the first point "Sort Order" above only applies to the structure hash, as the content hash doesn't hash any file names.

_Some more comments:_

On 1. Sort Order: For the content hashes we don't have anything else than the hashes, so that's required here to sort by hash. For the structure hash we need to hash the file names, the subdirectory names, and the structure hash of the subdirectories. So when we switch to "path" here, we would need to decide how to sort in the structure hashes of the subdirectories between the path names.

On 2. Content Deduplication: For structure hashes deduplication does nothing, as two files with the same _name_ should not exist in a directory. For content directory we can easily decide if we want to skip deduplication. Right now a folder with two identical files has the same content hash than another folder with three of these files. If that's not desired, we can remove the deduplication. It came from the C4 implementation.

On 3. Multiple passes over content: I think the rationale is that the algorithm creates the same result as if the single items had been hashed altogether as one piece of data (see [comment](https://github.com/ascmitc/mhl/blob/275820ba66c0a220bb3e5f9803a081efda257d7e/tests/test_hasher.py#L19) in code). Maybe that behavior is not necessary here. I will try to contact Erik Weaver for a comment on the rationale of that algorithm.

**Comment by ptrpfn** [comment]
Who wants to take a look at the implementation in PR #51 , here are some pointers:

The `DirectoryHashContext` class in [mhl/hasher.py](https://github.com/ascmitc/mhl/blob/dev/split-directory-hashes/mhl/hasher.py) collects all the hashes for a specific folder, and offers the following main functions:

* [append_directory_hashes](https://github.com/ascmitc/mhl/blob/275820ba66c0a220bb3e5f9803a081efda257d7e/mhl/hasher.py#L120): Used for adding information about file or subfolder. It requires the path name (relative in the folder), the content hash of the file (or the recursive content hash of a folder), and the structure hash (if it's a folder).
* [final_content_hash_str](https://github.com/ascmitc/mhl/blob/275820ba66c0a220bb3e5f9803a081efda257d7e/mhl/hasher.py#L125): Creates the content hash of (based on the stored content hashes)
* [final_structure_hash_str](https://github.com/ascmitc/mhl/blob/275820ba66c0a220bb3e5f9803a081efda257d7e/mhl/hasher.py#L131): Creates the structure hash (based on the paths and the stored structure hashes of subdirectories)

**Comment by ptrpfn** [comment]
I removed the link to the SMPTE standard, as this document cannot be shared publicly.

**Comment by mrjoshuak** [comment]
The mechanism that C4 uses to identify non contiguous data is designed around consistency and practicality.

The algorithm is invariant to metadata information such as filenames, and produces the same ID for the same content regardless of name changes sorting order or other factors. It removes duplicate content ids so file sets that differ only by repetition will also produce the same ID. 

The C4 algorithm is conducive to concurrent processing to a very high degree of granularity, and provides fast forward and reverse indexing, fast modification, optimized network communication, and fast validation. 

The C4 ID Tree is very similar to a Merkle tree, but introduces the idea of a global pool of tree nodes. Such a database can facilitate operations between large file sets like an object storage bucket or flat filesystem and a subset of those files. 

Another difference is that Merkle trees have an implied structure, content hashes are simply appended not sorted, making a Merkle tree very good at describing sequentially ordered data such as as file blocks or streaming data However, Merkle trees do not de-duplicate data, and my produce different root hashes for identical data especially in cases where the data has no implied order. 

Because a C4 ID Tree reorders hashes in the tree the order in which data is added is unimportant and not preserved. This means that the order or "meaning" of the data must be preserved elsewhere, but this is consistent with how C4 IDs work for files as well (i.e. filename and file data are decoupled).

For example one might use a C4 ID Tree to describe a very large filesystem. You'd end up with a flat list of C4 IDs for every unique file, and another file that describes what each file should be named and where it appears in the file system (potentially more than once).

I don't want to bore you with unnecessary detail (more than I have already), so tell me if there is something you're particularly interested in or is a concern for your use case.

**Comment by ptrpfn** [comment]
Thank you Joshua for the comprehensive overview of the design aspects of the C4 algorithms. I will take a look at our current implementation once more to see if we implemented the directory hashes (both the "content directory hashes" for the file contents as well as the "structure directory hashes" for the file names and subfolder structure) according to these concepts. 

You mentioned a few things that I was not aware of yet. For example right now we create content hashes of an entire file tree _per sub-directory_  – while it could make sense to discuss that _global pool_ kind of algorithm that you mention (depends if we mainly want to verify the content for the root hash, or of individual sub-directories).

This topic will be on the agenda of the working group meeting on 10. February, but I hope we will have some offline discussion before that. I will get back to you with individual questions as soon as they come up.

**Comment by jwaggs** [comment]
@mrjoshuak your write up was a huge help. Nothing boring at all!

It appears the intent of a c4 ID Tree as you mentioned is to produce an ID for a "global pool of tree nodes". In this use case, it makes sense for all of the files to be included in a flat list and deduplicated for computation of the global checksum value.

In our use case, at least until now, we had planned to include these "tree ids" at every directory level rather than just at the root global level. After running tests on the viability of computing a c4 Tree ID on a file system at each directory level, I noticed that the algorithm became more expensive the deeper the tree was. 

My preliminary findings is that the c4 Tree ID is too computationally expensive to be reasonably computed at EVERY directory level on a large file system due to the "re-inclusion" of each file hash redundantly up the tree structure. 

Our prior algorithm was much closer to a Merkle tree to avoid these issues since tree hashes were to be computed at every level.

@mrjoshuak You seem to indicate this algorithm was designed for use at the global level only, such as for entire s3 buckets or entire filesystems. Am I correct in assuming that the use case of computing a tree id at every directory level was not the intent of the c4 tree id system? 

@ptrpfn I feel we should define whether our use case requires these IDs to be computed at every level, or if we can instead get away with the computation of a global tree id only... This would remove the computation of tree IDs for all directories except for the root folder.

If we change to global computation of the tree checksums only, changing to the approach outline in the c4 algorithm becomes more viable in my opinion.

Once we determine that use case, I think we will have a better idea of whether we should deduplicate content as well.

**Comment by jwaggs** [comment]
The two competing algorithms are implemented in two separate branches right now.

1. `dev/split-directory-hashes`: This branch is the merkle tree approach.
2. `dev/split-directory-hashes-flatlist`: This branch is the c4 Tree ID approach.

I used the `time` unix command to measure the execution of the two implementations. For simplicity, I executed this against the mhl repository itself which has a little over 5000 files, all of which are small. I deleted all prior generations before each test.

Results as follows:

**MERKLE TREE**
_with directory hashes:_
```
./ascmhl.py create /Volumes/LaCie/STRUCTURE -h xxh64  1.81s user 0.61s system 97% cpu 2.480 total
```
_without directory hashes_:
```
./ascmhl.py create /Volumes/LaCie/STRUCTURE -h xxh64 --no_directory_hashes  1.69s user 0.62s system 98% cpu 2.338 total
```

Here we can see that we gained directory hashes at every level with essentially no penalty. 

**C4 TREE**
_with directory hashes:_
```
./ascmhl.py create /Volumes/LaCie/STRUCTURE -h xxh64  4.23s user 0.64s system 99% cpu 4.887 total
```
_without directory hashes_:
```
./ascmhl.py create /Volumes/LaCie/STRUCTURE -h xxh64 --no_directory_hashes  1.82s user 0.63s system 94% cpu 2.577 total
```

Here we can see a speed penalty when we switch to the C4 tree ID algorithm. This would matter far less if we didn't compute it at every directory level.

**Comment by mrjoshuak** [comment]
Sounds like something it going wrong. The computation for directory hash is extremely fast. In most cases it should be faster than computing a single file ID, because directory hashes are not bound by the storage IO.

**Comment by mrjoshuak** [comment]
> My preliminary findings is that the c4 Tree ID is too computationally expensive to be reasonably computed at EVERY directory level on a large file system due to the "re-inclusion" of each file hash redundantly up the tree structure.

@jwaggs I'm not sure what you mean by re-inclusion of file hashes. Files are only ever hashed once, and the ID is only ever used once to calculating the directory hash. 

> You seem to indicate this algorithm was designed for use at the global level only, such as for entire s3 buckets or entire filesystems. Am I correct in assuming that the use case of computing a tree id at every directory level was not the intent of the c4 tree id system?

It requires similar storage and effort in both contexts unless there is a great deal of duplication between directories (since in that case the flat version would save by eliminating that duplication). If you have 10 files in a directory and 90 files in the directory above it, the fact the 10 file directory is collapsed to a single ID saves the parent directory from having to do those 10 files the parent with 90 files and 1 directory has 91 ids to calculate and ID from. A flat list of the same file system is 100 files so 100 ids to calculate an ID from. It all works out to be about the same overall effort.

**Comment by jwaggs** [comment]
@mrjoshuak it sounds like we might actually be on the same page. We are definitely in agreement that files are only ever hashed once.

> If you have 10 files in a directory and 90 files in the directory above it, the fact the 10 file directory is collapsed to a single ID saves the parent directory from having to consider those 10 files.

This is actually in line with the existing functionality in this repository. I completely agree with your reasoning here and think there may have been a misunderstanding about what the c4 spec was proposing in the first place. The proposal to deviate from this was opened recently in the `dev/split-directory-hashes-flatlist` branch.

Just to be sure though, given a structure:
```
rootFolder
├── file1
└── folder1
    ├── file2
    └── folder2
        └── file3
```

@mrjoshuak are we in agreement that the rootFolder would compute its ID from 2 IDs (`file1` id and `folder1` id), rather than 3 IDs from all nested files flattened (`file1` id, `file2` id, and `file3` id)?

If in agreement, that is the existing functionality in the master branch and is also contained within the `dev/split-directory-hashes` branch. @ptrpfn I am of the impression that the algorithm in the `dev/split-directory-hashes` branch is superior to the one in `dev/split-directory-hashes-flatlist` for the reasons Joshua just outlined.

**Comment by jwaggs** [comment]
@mrjoshuak given your feedback. I've updated my comments above with a disclaimers since the algorithm being tested was not a true c4 Tree Id, and rather seems to have been a misunderstanding about the c4 spec.

**Comment by jwaggs** [comment]
Re-reading your message @mrjoshuak - I may need to clarify a bit more about your example ...

> It all works out to be about the same overall effort, 1 id from 100 ids, or 2 ids one from 10 ids and the other from 91 ids.

That specific example works out to be about the same overall effort only because the former doesn't compute the child directory tree id. In that example, the former generates 1 id and the latter generates 2 ids. In this former scenario, one of the directories would not have a tree id.

If 2 tree ids were generated in both scenarios, one for each folder, then the flat list algorithm would be almost twice as expensive, because it would compute 1 id from 91 ids and then the root id from 100 ids.

This is why I am against the flat list algorithm proposed in the `dev/split-directory-hashes-flatlist` branch.

**Comment by mrjoshuak** [comment]
I want to clarify a potential ambiguity around what C4 Tree refers to in this context as I answer your question about the "rootFolder" ID example above. A C4 Tree is a binary tree of hashes starting from *any* two or more hashes. It has no relationship to a file system tree. That's probably already understood, just want to be clear.

For the rootFolder ID, yes it is computed from the ID of file1 and the ID of folder1 **IF** your intent is to produce IDs for *every* folder.  However, it's up to you. You could just as easily chose not to produce IDs for every folder, in which case you'd have "rootFolder" ID that consists of file1, file2, and file3. As I pointed out above baring duplication the cost of these two identification strategies are equivalent. 

So why might you chose one strategy over another? It comes down to what is meaningful to identify in the the context of the application.

It may seem like an ID for every directory in a filesystem is the obvious choice, but if we're talking about something like an IMF package or an mac os application bundle which have sub-directories but no one is expected to need a reference to one of those sub-directories out side of the context of the bundle itself then a flat list style is probably the best choice. 

Conversely in an object storage system even though it's may seem like a flat list is the obvious choice one might want to create IDs for every directory as it would appear in a file system for faster direct access to meaningful subsets of objects. 

It's how one expects C4 IDs to be used that determines the most meaningful boundary for grouping. 

> If 2 tree ids were generated in both scenarios, one for each folder, then the flat list algorithm would be potentially much more expensive, because it would compute 1 id from the 10 ids and then the root id from 90 ids. 

For clarity I'll say... if 2 flat file lists ids where generated then yes that seems like unnecessary computation. I can't think of a context in which you'd want to have nested flat lists, I mean flat means flat right? It's not unimaginable that there might be some use case though.

Its probably appropriate to discuss the global node pool concept here. It's not necessary to for anything we're discussing at the moment but it can be used for optimization and indexing. I'll post that in a follow up.

**Comment by mrjoshuak** [comment]
Note regarding the ID per directory in an object storage system example.

These IDs would refer to a list of files that are not the same as the lists you'd get by matching keys to the path, because files in subfolders are excluded in the one, but not in the other. The ability to identify complex logical sets like this is part of c4's design. Leveraging that design relies on application developers making deliberate choices about what constitutes the most meaningful *atoms* of identification in the context of their application. You can be very flexible in your thinking about collections to identify, you needn't be bound to files and folders.

**Comment by jwaggs** [comment]
@mrjoshuak I agree with everything you've posted here.

> For clarity I'll say... if 2 flat file lists ids where generated where one is a subset of the other, then yes that seems like unnecessary computation. I can't think of a context in which you'd want to have nested flat lists like that. I mean flat means flat right?

I'd say this is the point I've really been trying to drive home @ptrpfn. This brings us back to the use cases. We need to decide whether we just want a root tree hash or a tree hash at each directory level.

> For the rootFolder ID, yes it is computed from the ID of file1 and the ID of folder1 IF your intent is to produce IDs for every folder. However, it's up to you. You could just as easily chose not to produce IDs for every folder, in which case you'd have a "rootFolder" ID that consists of file1, file2, and file3.

I agree with @mrjoshuak's assessment here, so in summary:

- If we go with root tree hash only then the flat list algorithm is viable.
- Else if we continue generating hashes at each directory level then we will also want to continue using those directory hash values in the calculation of their parent directory hashes (no flattening of list) to avoid unnecessary computation.

**Comment by ptrpfn** [comment]
I could just now follow-up your conversation about the technical implications of the different solutions. My view is very similar to what @jwaggs waggs lined out, but I want to add the findings about each solution from the previous conversations, as these might lead us to the right questions about what we actually want to solve with the directory hashes.

* **Recursive algorithm, root hash only**
	* moving a file folder up or down changes the root content hash
	* good performance
* **Recursive algorithm, every directory level**
	* moving a file folder up or down changes the top-level content hash
	* good performance (deeper directory hashes are reused)
* **Flat list algorithm, root hashes only**
	* implementation close to what C4 proposes
	* moving a file folder up or down leaves the root content hash unchanged
	* good performance
* **Flat list algorithm, every directory level**
	* implementation close to what C4 proposes
	* moving a file folder up or down leaves the top-level content hashes unchanged
	* longest computation time (same file hashes are part of multiple directory hash computations)

_Note: All four solutions are implemented in different branches as mentioned above in this conversation._

To move the discussion a bit away from the pure technical capabilities of each implementation, I would like to point out the questions that prevent us from choosing "the best" solution right away:

* **Shall the content directory change when files move up or down** a folder inside the folder structure? Or is that better covered by the structure directory hash? The structure directory hash is part of the directory hash proposal  and covers renaming of files.
* **Do we see a need to create directory hashes on each and every directory level?** What would be the use of all these content and structure hashes?

And one more, independent question that has not been discussed yet in this thread and that only really applies to "flat list" solutions:

* **Shall we de-duplicate the list of file hashes?** That would mean that no matter how many times one file appears in a folder structure, the top-level content directory hash stays the same.

@jwaggs If you could provide the example use cases where you see the main benefit of directory hashes, that help answering these questions (or bring up new ones). We started a similar document already with use cases for nesting as a base for discussio in the meeting. With such use cases written down I think it should be easy to answer the questions above and ultimately choose the right solution.

**Comment by jwaggs** [comment]
The main use case has been visual verifiability of an entire structure via checksum rather than requiring file by file visual verification of many checksums. This does not require directory checksums at each level. In fact, in the case that root checksums match, there is little to no value in the inclusion of sub-directory checksums. 

In the situation that a root checksum fails verification, the inclusion of sub-directory checksums would aid the end user in diagnosing or finding problematic directories, rather than just problematic files. That being said, I'm not sure this use case is strong enough to warrant the inclusion of directory checksums at each level.

I am ok with only generating 1 root content and 1 root structure hash per mhl generation because it solves our main use case.

**Comment by mrjoshuak** [comment]
> Shall the content directory change when files move up or down a folder inside the folder structure? 

Flat lists are only able to differentiate file addition and removal. 

Directory based identification can differentiate between "versions" of directories. This insures that a reference to a particular directory is absolute and immutable. After all what distinguishes a directory if not the files and folders it contains? Each change that is important to retain can be memorialized by associating a version label with particular Ids, and if only the last version is relevant then it's just as easy to discard any intermediate ids.

For C4 the idea is not only to validate data, but to support unanticipated discovery downstream. Someone downstream may have a directory of data and want to fined out more information about it. By computing the C4 ID for the directory they can then search available sources, including full text search of MHL files perhaps, and discover where the directory might have been referenced previously. Flat lists tend to this functionality more difficult because they only point to the entire fileset, not logically grouped subsets of files. 

> Do we see a need to create directory hashes on each and every directory level?

Since there is no appreciable cost difference I'd think one would prefer to provide the greatest level of support for unanticipated downstream use, so I'd argue yes you want to ID every directory and retain every meaningful "version" of directories as they change.

**Comment by ptrpfn** [comment]
With the pull request #51 and release 0.5.0 the directory hashes are implemented now. The algorithm still requires review, potentially best agains other, upcoming implementations to ensure that it conforms exactly to the specification.
